# 启动注册端口
server:
  port: 8090

#服务名
spring:
  application:
    name: third-part-index-data-server
  resources:
    static-locations: classpath:statics/

#eureka相关配置
eureka:
  client:
    service-url:
      defaultZone:
              http://localhost:8761/eureka