# 启动注册端口
server:
  port: 8031

#服务名
spring:
  application:
    name: index-zuul-service

#eureka相关配置
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/

# zuul 配置
zuul:
  routes:
      api-a:
        path: /api-codes/**
        serviceId: index-code-service
      api-b:
        path: /api-simulate/**
        serviceId: trend-trading-backtest-service
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    max-total-connections: 10000
    max-per-route-connections: 10000
  semaphore:
    max-semaphores: 200