# 启动注册端口
server:
  port: 8006

#服务名
spring:
  application:
    name:  trend-trading-backtest-service

#eureka相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign.hystrix.enabled: true