# 启动注册端口
server:
  port: 8010

#服务名
spring:
  application:
    name:  config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GM-Studio/trending
          username: 827321394@qq.com
          password: MRHSchen520
          search-paths: profiles
      label: master

#eureka相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

