# 启动注册端口
server:
  port: 8001

#服务名
spring:
  application:
    name: data-collection-storage-server

#eureka相关配置
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka